// <auto-generated />
namespace PassionProject_Barbershop_n01416375.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mvp4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mvp4));
        
        string IMigrationMetadata.Id
        {
            get { return "202102270403126_mvp4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
