// <auto-generated />
namespace PassionProject_Barbershop_n01416375.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class customers2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customers2));
        
        string IMigrationMetadata.Id
        {
            get { return "202103181617483_customers2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
