// <auto-generated />
namespace PassionProject_Barbershop_n01416375.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class customers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customers));
        
        string IMigrationMetadata.Id
        {
            get { return "202103180010136_customers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
