// <auto-generated />
namespace PassionProject_Barbershop_n01416375.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mvp2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mvp2));
        
        string IMigrationMetadata.Id
        {
            get { return "202102270351105_mvp2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
